ytvnr/gif-of-the-day

- front/package.json
add script in package json to run `npm start`
> chore: add start script 🏎🏎

- firebase.json
- front/package-lock.json
- package.json
> feat: init firebase scripts 🔥

- front/.gitignore
- front/src/firebaseConfig.json
- front/src/firebaseConfig.template.json
> fix: add firebase config 👌

- .github/workflows/on-push.yml
> fix: deploy only hosting 🎡

- .github/labels.yml
- .github/workflows/pull_request_labeler.yml
Auto label the PR based on the branch name
> chore: auto label PR

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
Here is a first version of PR template
> docs: add pull request template and documentation 👨‍🏫

- front/package-lock.json
- front/package.json
Upgrade serialize js and plugins to be more security compliant
> feat: upgrade serialize js and vue plugins 👁

- front/package-lock.json
- front/src/views/Gifs.vue
Use awesome editable table for displaying the giffy week
> feat: use vuetify editable table

- front/src/App.vue
- front/src/components/Drawer.vue
- front/src/router/index.js
- front/src/views/About.vue
- front/src/views/Login.vue
- front/src/views/Logout.vue
> feat: restrict page access 👮‍♂️

- front/src/components/TeamCard.vue
- front/src/views/Teams.vue
Provide a better UI for team card.
⚠️⚠️We will have to emit an event when a team is leaved/joined to provide a better UX (see https://github.com/ytvnr/gif-of-the-day/issues/51)⚠️⚠️
> feat: rework on team card

- front/src/components/TeamCard.vue
- front/src/store/index.js
- front/src/views/Logout.vue
Use store to manage assignedTeamId and make the "Join page" in real time and good state
> feat: use store for assignedTeamId v2

- firestore.rules
> chore: secure database access

- firestore.rules
- front/package-lock.json
- front/src/store/index.js
On registration, verify if user mail domain is authorized by the app (defined by database collection `authorizedDomains`)
> feat: register only if mail domain is authorized

- front/src/App.vue
- front/src/components/Drawer.vue
- front/src/components/NavBar.vue
- front/src/components/TeamCard.vue
- front/src/views/Home.vue
- front/src/views/Logout.vue
- front/src/views/Register.vue
- front/src/views/Schedule.vue
- front/src/views/Teams.vue
Build fail, due to not linting files 😢
> fix: apply lint fix on all files 💂🏼‍♂️

- front/package-lock.json
- front/package.json
- front/src/store/index.js
- front/src/views/Home.vue
#28 
[Issue] -> We lost the state for assignedTeamId or other objects from store. Only User is kept because we autologin.
[Resolution] -> Use `vuex-persistedstate` to use sessionStorage
> fix: keep state when refreshing using sessionStorage

- .github/workflows/staging-pr.yml
Build project before merging PR to avoid fail when deploy
> chore: build before merge

- firestore.rules
- front/package-lock.json
- front/src/components/TeamCard.vue
- front/src/store/index.js
- front/src/views/Home.vue
- front/src/views/Schedule.vue
- front/src/views/Teams.vue
As a user i can see all themes for this assigned team.
> Display gif themes by teams

- front/package-lock.json
- front/package.json
- front/src/views/Home.vue
#54 #74 
Use vuetify horizontal cards to rework home page.
- On display the user displayName or email. If user associated to a team, we display a random phrase for the day, like fortune.
- Second card display the team assigned to user. If not, a button appears to join a team.
- Last card display the theme of the day. With just above a random gif concerning this theme.
⚠️⚠️ Random phrase and gif theme are hardcoded for the moment ⚠️⚠️
🚨🚧 I had prettier as a devDependency to be able to use it 🚧🚨
> feat: use tiles for home page 💄👀

- front/package-lock.json
- front/src/services/giphy.service.js
- front/src/views/Home.vue
I want to see an example of gif for today on the home page
> feat: display a random gif matching theme of the day on home page 💅

- front/src/services/teams.service.js
- front/src/views/Gifs.vue
If a theme has been decided for my team today, I want to have it by default in the Gif page
> feat: theme of the day as default value in search input 💪

- front/src/firebase/init.js
- front/src/router/index.js
- front/src/services/teams.service.js
- front/src/views/Home.vue
- front/src/views/Schedule.vue
> Some fix and features

- front/src/views/Login.vue
When logging in I want to be able to submit with "Enter" key.
> feat: can submit with enter when logging in 🤡

- front/src/components/Drawer.vue
- front/src/router/index.js
- front/src/views/Faq.vue
A awesome page to display a FAQ !
> feat: init first version of FAQ 🧾

- LICENSE
> doc: Create LICENSE

- CONTRIBUTING.md
- README.md
Fixes #75 
Provide a better documentation in README and CONTRIBUTING
> doc: update readme and contributing

- front/.eslintrc.js
- front/src/views/About.vue
- front/src/views/Home.vue
Some time, in the home page data or not load.. We need to load each mounted time to prevent this bug :/ 
Bonus: externalize eslint config in file / remove console.log
> fix: load data on mounted 🤔

- front/src/App.vue
- front/src/store/index.js
Display a loader when store status is set to loading.
> fix: overlay when status is loading in store

- front/src/views/Schedule.vue
Fix column width in schedule page
> fix: schedule fixed column width

- .github/workflows/on-push.yml
CI is broken due to bad formating in #119
> fix: wording in action

- front/src/router/index.js
> chore: clean router

- front/src/components/GiphyPowered.vue
- front/src/components/TeamCard.vue
- front/src/views/Home.vue
- front/src/views/Schedule.vue
- front/src/views/Teams.vue
Convert giphy copyright to overlay 👻:
and
Switch week easily 📆
Update teams list cards size 📏
> feat: week-end improvements 👌 

- front/src/views/Schedule.vue
Fix a bug which prevent from being able to select a theme in the future
> fix: be able to select date in the future

- extension/local/manifest.json
- extension/staging/manifest.json
Change the description of local and staging extension to make it easy to use in chrome
> chore: change description for local and staging extension 👀

- bbl/slides/asciidoc/chapters/technical/vue.adoc
> feat: start  bbl vuejs intro 👌
